### ISSUE TITLE
MP Productions Test Alert

### ISSUE THREAD

**Issue by mattfleaydaly** [matfleaydaly/newstatuslive#11]
This is a test alert. Thank you - MPSA `<br>`
UPDATE 12/10/2016: We are still testing. Thank you. - MPSA

**Comment by matfleaydaly** [comment]
We are working on this issue still. Thank you - MPSA

**Comment by marcel-dias** [comment]
Hey @matfleaydaly
I tryied to reply your email, but your server is not delivering it. 

I've integrated my github repository(https://github.com/marceldiass/StatusTest) with the https://www.netlify.com service. Then modified the webhook to handle just "Issues" events.

To setup the build I added those files: requirements.txt  runtime.txt to the github repository. You can copy from https://github.com/marceldiass/StatusTest/blob/gh-pages/requirements.txt and https://github.com/marceldiass/StatusTest/blob/gh-pages/runtime.txt

At Netlify I configured with:
branch: gh-pages
cmd command:  statuspage update --name=$GH_REPO_NAME --token=$GH_TOKEN
And there is Build environments to configure GH_REPO_NAME e GH_TOKEN variables.

And is it. 

Cheers.
Marcel Dias
