### ISSUE TITLE
BCSV Website Maintenance Update

### ISSUE THREAD

**Issue by mattfleaydaly** [matfleaydaly/newstatuslive#36]
We've got some Planned Maintenance for the BCSV Website. <br>
This will include just an update of the splash screen as requested. <br>
Thank You. - MPM

**Comment by matfleaydaly** [comment]
We will be starting these maintenance works shortly. <be>
They won't take too long to complete. <be>
Thank You. - MPM

**Comment by mattfleaydaly** [comment]
We will be starting the Maintenance Works to the BCSV Website at approximately 11:00PM AEST Tonight. <br>
These works should not take longer than 15 minutes. <br>
Thank You. - MPM

**Comment by mattfleaydaly** [comment]
Maintenance Now In Progress. <br>
Scotty will be back shortly... - MPM

**Comment by mattfleaydaly** [comment]
Maintenance is now complete. <br>
No need to fear, the BCSV Website is now fully up to date! <br>
Thanks. - MPM
